export interface Country {
  code: string; // ISO 3166-1 alpha-2 country code
  en: string;
  ar: string;
  value: string;
  phoneCode: string;
}

// Sorted alphabetically by English name
export const COUNTRIES: Country[] = [
  { code: 'AF', en: 'Afghanistan', ar: 'أفغانستان', value: 'Afghanistan', phoneCode: '93' },
  { code: 'AL', en: 'Albania', ar: 'ألبانيا', value: 'Albania', phoneCode: '355' },
  { code: 'DZ', en: 'Algeria', ar: 'الجزائر', value: 'Algeria', phoneCode: '213' },
  { code: 'AD', en: 'Andorra', ar: 'أندورا', value: 'Andorra', phoneCode: '376' },
  { code: 'AO', en: 'Angola', ar: 'أنغولا', value: 'Angola', phoneCode: '244' },
  { code: 'AR', en: 'Argentina', ar: 'الأرجنتين', value: 'Argentina', phoneCode: '54' },
  { code: 'AM', en: 'Armenia', ar: 'أرمينيا', value: 'Armenia', phoneCode: '374' },
  { code: 'AU', en: 'Australia', ar: 'أستراليا', value: 'Australia', phoneCode: '61' },
  { code: 'AT', en: 'Austria', ar: 'النمسا', value: 'Austria', phoneCode: '43' },
  { code: 'AZ', en: 'Azerbaijan', ar: 'أذربيجان', value: 'Azerbaijan', phoneCode: '994' },
  { code: 'BH', en: 'Bahrain', ar: 'البحرين', value: 'Bahrain', phoneCode: '973' },
  { code: 'BD', en: 'Bangladesh', ar: 'بنغلاديش', value: 'Bangladesh', phoneCode: '880' },
  { code: 'BY', en: 'Belarus', ar: 'بيلاروسيا', value: 'Belarus', phoneCode: '375' },
  { code: 'BE', en: 'Belgium', ar: 'بلجيكا', value: 'Belgium', phoneCode: '32' },
  { code: 'BZ', en: 'Belize', ar: 'بليز', value: 'Belize', phoneCode: '501' },
  { code: 'BJ', en: 'Benin', ar: 'بنين', value: 'Benin', phoneCode: '229' },
  { code: 'BO', en: 'Bolivia', ar: 'بوليفيا', value: 'Bolivia', phoneCode: '591' },
  {
    code: 'BA',
    en: 'Bosnia and Herzegovina',
    ar: 'البوسنة والهرسك',
    value: 'Bosnia and Herzegovina',
    phoneCode: '387',
  },
  { code: 'BW', en: 'Botswana', ar: 'بوتسوانا', value: 'Botswana', phoneCode: '267' },
  { code: 'BR', en: 'Brazil', ar: 'البرازيل', value: 'Brazil', phoneCode: '55' },
  { code: 'BN', en: 'Brunei', ar: 'بروناي', value: 'Brunei', phoneCode: '673' },
  { code: 'BG', en: 'Bulgaria', ar: 'بلغاريا', value: 'Bulgaria', phoneCode: '359' },
  { code: 'BF', en: 'Burkina Faso', ar: 'بوركينا فاسو', value: 'Burkina Faso', phoneCode: '226' },
  { code: 'KH', en: 'Cambodia', ar: 'كمبوديا', value: 'Cambodia', phoneCode: '855' },
  { code: 'CM', en: 'Cameroon', ar: 'الكاميرون', value: 'Cameroon', phoneCode: '237' },
  { code: 'CA', en: 'Canada', ar: 'كندا', value: 'Canada', phoneCode: '1' },
  { code: 'CL', en: 'Chile', ar: 'تشيلي', value: 'Chile', phoneCode: '56' },
  { code: 'CN', en: 'China', ar: 'الصين', value: 'China', phoneCode: '86' },
  { code: 'CO', en: 'Colombia', ar: 'كولومبيا', value: 'Colombia', phoneCode: '57' },
  {
    code: 'CD',
    en: 'Congo (DRC)',
    ar: 'الكونغو الديمقراطية',
    value: 'Congo (DRC)',
    phoneCode: '243',
  },
  { code: 'CR', en: 'Costa Rica', ar: 'كوستاريكا', value: 'Costa Rica', phoneCode: '506' },
  { code: 'HR', en: 'Croatia', ar: 'كرواتيا', value: 'Croatia', phoneCode: '385' },
  { code: 'CU', en: 'Cuba', ar: 'كوبا', value: 'Cuba', phoneCode: '53' },
  { code: 'CY', en: 'Cyprus', ar: 'قبرص', value: 'Cyprus', phoneCode: '357' },
  { code: 'CZ', en: 'Czech Republic', ar: 'التشيك', value: 'Czech Republic', phoneCode: '420' },
  { code: 'DK', en: 'Denmark', ar: 'الدنمارك', value: 'Denmark', phoneCode: '45' },
  { code: 'DJ', en: 'Djibouti', ar: 'جيبوتي', value: 'Djibouti', phoneCode: '253' },
  {
    code: 'DO',
    en: 'Dominican Republic',
    ar: 'جمهورية الدومينيكان',
    value: 'Dominican Republic',
    phoneCode: '1',
  },
  { code: 'EC', en: 'Ecuador', ar: 'الإكوادور', value: 'Ecuador', phoneCode: '593' },
  { code: 'EG', en: 'Egypt', ar: 'مصر', value: 'Egypt', phoneCode: '20' },
  { code: 'SV', en: 'El Salvador', ar: 'السلفادور', value: 'El Salvador', phoneCode: '503' },
  { code: 'ER', en: 'Eritrea', ar: 'إريتريا', value: 'Eritrea', phoneCode: '291' },
  { code: 'EE', en: 'Estonia', ar: 'إستونيا', value: 'Estonia', phoneCode: '372' },
  { code: 'ET', en: 'Ethiopia', ar: 'إثيوبيا', value: 'Ethiopia', phoneCode: '251' },
  { code: 'FI', en: 'Finland', ar: 'فنلندا', value: 'Finland', phoneCode: '358' },
  { code: 'FR', en: 'France', ar: 'فرنسا', value: 'France', phoneCode: '33' },
  { code: 'GE', en: 'Georgia', ar: 'جورجيا', value: 'Georgia', phoneCode: '995' },
  { code: 'DE', en: 'Germany', ar: 'ألمانيا', value: 'Germany', phoneCode: '49' },
  { code: 'GH', en: 'Ghana', ar: 'غانا', value: 'Ghana', phoneCode: '233' },
  { code: 'GR', en: 'Greece', ar: 'اليونان', value: 'Greece', phoneCode: '30' },
  { code: 'GT', en: 'Guatemala', ar: 'غواتيمالا', value: 'Guatemala', phoneCode: '502' },
  { code: 'GN', en: 'Guinea', ar: 'غينيا', value: 'Guinea', phoneCode: '224' },
  { code: 'HT', en: 'Haiti', ar: 'هايتي', value: 'Haiti', phoneCode: '509' },
  { code: 'HN', en: 'Honduras', ar: 'هندوراس', value: 'Honduras', phoneCode: '504' },
  { code: 'HK', en: 'Hong Kong', ar: 'هونغ كونغ', value: 'Hong Kong', phoneCode: '852' },
  { code: 'HU', en: 'Hungary', ar: 'المجر', value: 'Hungary', phoneCode: '36' },
  { code: 'IS', en: 'Iceland', ar: 'آيسلندا', value: 'Iceland', phoneCode: '354' },
  { code: 'IN', en: 'India', ar: 'الهند', value: 'India', phoneCode: '91' },
  { code: 'ID', en: 'Indonesia', ar: 'إندونيسيا', value: 'Indonesia', phoneCode: '62' },
  { code: 'IR', en: 'Iran', ar: 'إيران', value: 'Iran', phoneCode: '98' },
  { code: 'IQ', en: 'Iraq', ar: 'العراق', value: 'Iraq', phoneCode: '964' },
  { code: 'IE', en: 'Ireland', ar: 'أيرلندا', value: 'Ireland', phoneCode: '353' },
  { code: 'IL', en: 'Israel', ar: 'إسرائيل', value: 'Israel', phoneCode: '972' },
  { code: 'IT', en: 'Italy', ar: 'إيطاليا', value: 'Italy', phoneCode: '39' },
  { code: 'JM', en: 'Jamaica', ar: 'جامايكا', value: 'Jamaica', phoneCode: '1' },
  { code: 'JP', en: 'Japan', ar: 'اليابان', value: 'Japan', phoneCode: '81' },
  { code: 'JO', en: 'Jordan', ar: 'الأردن', value: 'Jordan', phoneCode: '962' },
  { code: 'KZ', en: 'Kazakhstan', ar: 'كازاخستان', value: 'Kazakhstan', phoneCode: '7' },
  { code: 'KE', en: 'Kenya', ar: 'كينيا', value: 'Kenya', phoneCode: '254' },
  { code: 'KW', en: 'Kuwait', ar: 'الكويت', value: 'Kuwait', phoneCode: '965' },
  { code: 'KG', en: 'Kyrgyzstan', ar: 'قيرغيزستان', value: 'Kyrgyzstan', phoneCode: '996' },
  { code: 'LA', en: 'Laos', ar: 'لاوس', value: 'Laos', phoneCode: '856' },
  { code: 'LV', en: 'Latvia', ar: 'لاتفيا', value: 'Latvia', phoneCode: '371' },
  { code: 'LB', en: 'Lebanon', ar: 'لبنان', value: 'Lebanon', phoneCode: '961' },
  { code: 'LY', en: 'Libya', ar: 'ليبيا', value: 'Libya', phoneCode: '218' },
  { code: 'LT', en: 'Lithuania', ar: 'ليتوانيا', value: 'Lithuania', phoneCode: '370' },
  { code: 'LU', en: 'Luxembourg', ar: 'لوكسمبورغ', value: 'Luxembourg', phoneCode: '352' },
  { code: 'MG', en: 'Madagascar', ar: 'مدغشقر', value: 'Madagascar', phoneCode: '261' },
  { code: 'MY', en: 'Malaysia', ar: 'ماليزيا', value: 'Malaysia', phoneCode: '60' },
  { code: 'ML', en: 'Mali', ar: 'مالي', value: 'Mali', phoneCode: '223' },
  { code: 'MT', en: 'Malta', ar: 'مالطا', value: 'Malta', phoneCode: '356' },
  { code: 'MR', en: 'Mauritania', ar: 'موريتانيا', value: 'Mauritania', phoneCode: '222' },
  { code: 'MU', en: 'Mauritius', ar: 'موريشيوس', value: 'Mauritius', phoneCode: '230' },
  { code: 'MX', en: 'Mexico', ar: 'المكسيك', value: 'Mexico', phoneCode: '52' },
  { code: 'MD', en: 'Moldova', ar: 'مولدوفا', value: 'Moldova', phoneCode: '373' },
  { code: 'MN', en: 'Mongolia', ar: 'منغوليا', value: 'Mongolia', phoneCode: '976' },
  { code: 'ME', en: 'Montenegro', ar: 'الجبل الأسود', value: 'Montenegro', phoneCode: '382' },
  { code: 'MA', en: 'Morocco', ar: 'المغرب', value: 'Morocco', phoneCode: '212' },
  { code: 'MZ', en: 'Mozambique', ar: 'موزمبيق', value: 'Mozambique', phoneCode: '258' },
  { code: 'MM', en: 'Myanmar', ar: 'ميانمار', value: 'Myanmar', phoneCode: '95' },
  { code: 'NA', en: 'Namibia', ar: 'ناميبيا', value: 'Namibia', phoneCode: '264' },
  { code: 'NP', en: 'Nepal', ar: 'نيبال', value: 'Nepal', phoneCode: '977' },
  { code: 'NL', en: 'Netherlands', ar: 'هولندا', value: 'Netherlands', phoneCode: '31' },
  { code: 'NZ', en: 'New Zealand', ar: 'نيوزيلندا', value: 'New Zealand', phoneCode: '64' },
  { code: 'NI', en: 'Nicaragua', ar: 'نيكاراغوا', value: 'Nicaragua', phoneCode: '505' },
  { code: 'NE', en: 'Niger', ar: 'النيجر', value: 'Niger', phoneCode: '227' },
  { code: 'NG', en: 'Nigeria', ar: 'نيجيريا', value: 'Nigeria', phoneCode: '234' },
  { code: 'KP', en: 'North Korea', ar: 'كوريا الشمالية', value: 'North Korea', phoneCode: '850' },
  {
    code: 'MK',
    en: 'North Macedonia',
    ar: 'مقدونيا الشمالية',
    value: 'North Macedonia',
    phoneCode: '389',
  },
  { code: 'NO', en: 'Norway', ar: 'النرويج', value: 'Norway', phoneCode: '47' },
  { code: 'OM', en: 'Oman', ar: 'عمان', value: 'Oman', phoneCode: '968' },
  { code: 'PK', en: 'Pakistan', ar: 'باكستان', value: 'Pakistan', phoneCode: '92' },
  { code: 'PS', en: 'Palestine', ar: 'فلسطين', value: 'Palestine', phoneCode: '970' },
  { code: 'PA', en: 'Panama', ar: 'بنما', value: 'Panama', phoneCode: '507' },
  { code: 'PY', en: 'Paraguay', ar: 'باراغواي', value: 'Paraguay', phoneCode: '595' },
  { code: 'PE', en: 'Peru', ar: 'بيرو', value: 'Peru', phoneCode: '51' },
  { code: 'PH', en: 'Philippines', ar: 'الفلبين', value: 'Philippines', phoneCode: '63' },
  { code: 'PL', en: 'Poland', ar: 'بولندا', value: 'Poland', phoneCode: '48' },
  { code: 'PT', en: 'Portugal', ar: 'البرتغال', value: 'Portugal', phoneCode: '351' },
  { code: 'QA', en: 'Qatar', ar: 'قطر', value: 'Qatar', phoneCode: '974' },
  { code: 'RO', en: 'Romania', ar: 'رومانيا', value: 'Romania', phoneCode: '40' },
  { code: 'RU', en: 'Russia', ar: 'روسيا', value: 'Russia', phoneCode: '7' },
  { code: 'RW', en: 'Rwanda', ar: 'رواندا', value: 'Rwanda', phoneCode: '250' },
  {
    code: 'SA',
    en: 'Saudi Arabia',
    ar: 'المملكة العربية السعودية',
    value: 'Saudi Arabia',
    phoneCode: '966',
  },
  { code: 'SN', en: 'Senegal', ar: 'السنغال', value: 'Senegal', phoneCode: '221' },
  { code: 'RS', en: 'Serbia', ar: 'صربيا', value: 'Serbia', phoneCode: '381' },
  { code: 'SG', en: 'Singapore', ar: 'سنغافورة', value: 'Singapore', phoneCode: '65' },
  { code: 'SK', en: 'Slovakia', ar: 'سلوفاكيا', value: 'Slovakia', phoneCode: '421' },
  { code: 'SI', en: 'Slovenia', ar: 'سلوفينيا', value: 'Slovenia', phoneCode: '386' },
  { code: 'SO', en: 'Somalia', ar: 'الصومال', value: 'Somalia', phoneCode: '252' },
  { code: 'ZA', en: 'South Africa', ar: 'جنوب أفريقيا', value: 'South Africa', phoneCode: '27' },
  { code: 'KR', en: 'South Korea', ar: 'كوريا الجنوبية', value: 'South Korea', phoneCode: '82' },
  { code: 'SS', en: 'South Sudan', ar: 'جنوب السودان', value: 'South Sudan', phoneCode: '211' },
  { code: 'ES', en: 'Spain', ar: 'إسبانيا', value: 'Spain', phoneCode: '34' },
  { code: 'LK', en: 'Sri Lanka', ar: 'سريلانكا', value: 'Sri Lanka', phoneCode: '94' },
  { code: 'SD', en: 'Sudan', ar: 'السودان', value: 'Sudan', phoneCode: '249' },
  { code: 'SE', en: 'Sweden', ar: 'السويد', value: 'Sweden', phoneCode: '46' },
  { code: 'CH', en: 'Switzerland', ar: 'سويسرا', value: 'Switzerland', phoneCode: '41' },
  { code: 'SY', en: 'Syria', ar: 'سوريا', value: 'Syria', phoneCode: '963' },
  { code: 'TW', en: 'Taiwan', ar: 'تايوان', value: 'Taiwan', phoneCode: '886' },
  { code: 'TJ', en: 'Tajikistan', ar: 'طاجيكستان', value: 'Tajikistan', phoneCode: '992' },
  { code: 'TZ', en: 'Tanzania', ar: 'تنزانيا', value: 'Tanzania', phoneCode: '255' },
  { code: 'TH', en: 'Thailand', ar: 'تايلاند', value: 'Thailand', phoneCode: '66' },
  { code: 'TN', en: 'Tunisia', ar: 'تونس', value: 'Tunisia', phoneCode: '216' },
  { code: 'TR', en: 'Turkey', ar: 'تركيا', value: 'Turkey', phoneCode: '90' },
  { code: 'TM', en: 'Turkmenistan', ar: 'تركمانستان', value: 'Turkmenistan', phoneCode: '993' },
  { code: 'UG', en: 'Uganda', ar: 'أوغندا', value: 'Uganda', phoneCode: '256' },
  { code: 'UA', en: 'Ukraine', ar: 'أوكرانيا', value: 'Ukraine', phoneCode: '380' },
  {
    code: 'AE',
    en: 'United Arab Emirates',
    ar: 'الإمارات العربية المتحدة',
    value: 'United Arab Emirates',
    phoneCode: '971',
  },
  {
    code: 'GB',
    en: 'United Kingdom',
    ar: 'المملكة المتحدة',
    value: 'United Kingdom',
    phoneCode: '44',
  },
  {
    code: 'US',
    en: 'United States',
    ar: 'الولايات المتحدة',
    value: 'United States',
    phoneCode: '1',
  },
  { code: 'UY', en: 'Uruguay', ar: 'أوروغواي', value: 'Uruguay', phoneCode: '598' },
  { code: 'UZ', en: 'Uzbekistan', ar: 'أوزبكستان', value: 'Uzbekistan', phoneCode: '998' },
  { code: 'VE', en: 'Venezuela', ar: 'فنزويلا', value: 'Venezuela', phoneCode: '58' },
  { code: 'VN', en: 'Vietnam', ar: 'فيتنام', value: 'Vietnam', phoneCode: '84' },
  { code: 'YE', en: 'Yemen', ar: 'اليمن', value: 'Yemen', phoneCode: '967' },
  { code: 'ZM', en: 'Zambia', ar: 'زامبيا', value: 'Zambia', phoneCode: '260' },
  { code: 'ZW', en: 'Zimbabwe', ar: 'زيمبابوي', value: 'Zimbabwe', phoneCode: '263' },
];

/**
 * Get country name by ISO country code
 */
export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find((country) => country.code === code.toUpperCase());
}
