export interface Country {
  code: string; // ISO 3166-1 alpha-2 country code
  en: string;
  ar: string;
  value: string;
}

// Sorted alphabetically by English name
export const COUNTRIES: Country[] = [
  { code: 'AF', en: 'Afghanistan', ar: 'أفغانستان', value: 'Afghanistan' },
  { code: 'AL', en: 'Albania', ar: 'ألبانيا', value: 'Albania' },
  { code: 'DZ', en: 'Algeria', ar: 'الجزائر', value: 'Algeria' },
  { code: 'AD', en: 'Andorra', ar: 'أندورا', value: 'Andorra' },
  { code: 'AO', en: 'Angola', ar: 'أنغولا', value: 'Angola' },
  { code: 'AR', en: 'Argentina', ar: 'الأرجنتين', value: 'Argentina' },
  { code: 'AM', en: 'Armenia', ar: 'أرمينيا', value: 'Armenia' },
  { code: 'AU', en: 'Australia', ar: 'أستراليا', value: 'Australia' },
  { code: 'AT', en: 'Austria', ar: 'النمسا', value: 'Austria' },
  { code: 'AZ', en: 'Azerbaijan', ar: 'أذربيجان', value: 'Azerbaijan' },
  { code: 'BH', en: 'Bahrain', ar: 'البحرين', value: 'Bahrain' },
  { code: 'BD', en: 'Bangladesh', ar: 'بنغلاديش', value: 'Bangladesh' },
  { code: 'BY', en: 'Belarus', ar: 'بيلاروسيا', value: 'Belarus' },
  { code: 'BE', en: 'Belgium', ar: 'بلجيكا', value: 'Belgium' },
  { code: 'BZ', en: 'Belize', ar: 'بليز', value: 'Belize' },
  { code: 'BJ', en: 'Benin', ar: 'بنين', value: 'Benin' },
  { code: 'BO', en: 'Bolivia', ar: 'بوليفيا', value: 'Bolivia' },
  {
    code: 'BA',
    en: 'Bosnia and Herzegovina',
    ar: 'البوسنة والهرسك',
    value: 'Bosnia and Herzegovina',
  },
  { code: 'BW', en: 'Botswana', ar: 'بوتسوانا', value: 'Botswana' },
  { code: 'BR', en: 'Brazil', ar: 'البرازيل', value: 'Brazil' },
  { code: 'BN', en: 'Brunei', ar: 'بروناي', value: 'Brunei' },
  { code: 'BG', en: 'Bulgaria', ar: 'بلغاريا', value: 'Bulgaria' },
  { code: 'BF', en: 'Burkina Faso', ar: 'بوركينا فاسو', value: 'Burkina Faso' },
  { code: 'KH', en: 'Cambodia', ar: 'كمبوديا', value: 'Cambodia' },
  { code: 'CM', en: 'Cameroon', ar: 'الكاميرون', value: 'Cameroon' },
  { code: 'CA', en: 'Canada', ar: 'كندا', value: 'Canada' },
  { code: 'CL', en: 'Chile', ar: 'تشيلي', value: 'Chile' },
  { code: 'CN', en: 'China', ar: 'الصين', value: 'China' },
  { code: 'CO', en: 'Colombia', ar: 'كولومبيا', value: 'Colombia' },
  {
    code: 'CD',
    en: 'Congo (DRC)',
    ar: 'الكونغو الديمقراطية',
    value: 'Congo (DRC)',
  },
  { code: 'CR', en: 'Costa Rica', ar: 'كوستاريكا', value: 'Costa Rica' },
  { code: 'HR', en: 'Croatia', ar: 'كرواتيا', value: 'Croatia' },
  { code: 'CU', en: 'Cuba', ar: 'كوبا', value: 'Cuba' },
  { code: 'CY', en: 'Cyprus', ar: 'قبرص', value: 'Cyprus' },
  { code: 'CZ', en: 'Czech Republic', ar: 'التشيك', value: 'Czech Republic' },
  { code: 'DK', en: 'Denmark', ar: 'الدنمارك', value: 'Denmark' },
  { code: 'DJ', en: 'Djibouti', ar: 'جيبوتي', value: 'Djibouti' },
  {
    code: 'DO',
    en: 'Dominican Republic',
    ar: 'جمهورية الدومينيكان',
    value: 'Dominican Republic',
  },
  { code: 'EC', en: 'Ecuador', ar: 'الإكوادور', value: 'Ecuador' },
  { code: 'EG', en: 'Egypt', ar: 'مصر', value: 'Egypt' },
  { code: 'SV', en: 'El Salvador', ar: 'السلفادور', value: 'El Salvador' },
  { code: 'ER', en: 'Eritrea', ar: 'إريتريا', value: 'Eritrea' },
  { code: 'EE', en: 'Estonia', ar: 'إستونيا', value: 'Estonia' },
  { code: 'ET', en: 'Ethiopia', ar: 'إثيوبيا', value: 'Ethiopia' },
  { code: 'FI', en: 'Finland', ar: 'فنلندا', value: 'Finland' },
  { code: 'FR', en: 'France', ar: 'فرنسا', value: 'France' },
  { code: 'GE', en: 'Georgia', ar: 'جورجيا', value: 'Georgia' },
  { code: 'DE', en: 'Germany', ar: 'ألمانيا', value: 'Germany' },
  { code: 'GH', en: 'Ghana', ar: 'غانا', value: 'Ghana' },
  { code: 'GR', en: 'Greece', ar: 'اليونان', value: 'Greece' },
  { code: 'GT', en: 'Guatemala', ar: 'غواتيمالا', value: 'Guatemala' },
  { code: 'GN', en: 'Guinea', ar: 'غينيا', value: 'Guinea' },
  { code: 'HT', en: 'Haiti', ar: 'هايتي', value: 'Haiti' },
  { code: 'HN', en: 'Honduras', ar: 'هندوراس', value: 'Honduras' },
  { code: 'HK', en: 'Hong Kong', ar: 'هونغ كونغ', value: 'Hong Kong' },
  { code: 'HU', en: 'Hungary', ar: 'المجر', value: 'Hungary' },
  { code: 'IS', en: 'Iceland', ar: 'آيسلندا', value: 'Iceland' },
  { code: 'IN', en: 'India', ar: 'الهند', value: 'India' },
  { code: 'ID', en: 'Indonesia', ar: 'إندونيسيا', value: 'Indonesia' },
  { code: 'IR', en: 'Iran', ar: 'إيران', value: 'Iran' },
  { code: 'IQ', en: 'Iraq', ar: 'العراق', value: 'Iraq' },
  { code: 'IE', en: 'Ireland', ar: 'أيرلندا', value: 'Ireland' },
  { code: 'IL', en: 'Israel', ar: 'إسرائيل', value: 'Israel' },
  { code: 'IT', en: 'Italy', ar: 'إيطاليا', value: 'Italy' },
  { code: 'JM', en: 'Jamaica', ar: 'جامايكا', value: 'Jamaica' },
  { code: 'JP', en: 'Japan', ar: 'اليابان', value: 'Japan' },
  { code: 'JO', en: 'Jordan', ar: 'الأردن', value: 'Jordan' },
  { code: 'KZ', en: 'Kazakhstan', ar: 'كازاخستان', value: 'Kazakhstan' },
  { code: 'KE', en: 'Kenya', ar: 'كينيا', value: 'Kenya' },
  { code: 'KW', en: 'Kuwait', ar: 'الكويت', value: 'Kuwait' },
  { code: 'KG', en: 'Kyrgyzstan', ar: 'قيرغيزستان', value: 'Kyrgyzstan' },
  { code: 'LA', en: 'Laos', ar: 'لاوس', value: 'Laos' },
  { code: 'LV', en: 'Latvia', ar: 'لاتفيا', value: 'Latvia' },
  { code: 'LB', en: 'Lebanon', ar: 'لبنان', value: 'Lebanon' },
  { code: 'LY', en: 'Libya', ar: 'ليبيا', value: 'Libya' },
  { code: 'LT', en: 'Lithuania', ar: 'ليتوانيا', value: 'Lithuania' },
  { code: 'LU', en: 'Luxembourg', ar: 'لوكسمبورغ', value: 'Luxembourg' },
  { code: 'MG', en: 'Madagascar', ar: 'مدغشقر', value: 'Madagascar' },
  { code: 'MY', en: 'Malaysia', ar: 'ماليزيا', value: 'Malaysia' },
  { code: 'ML', en: 'Mali', ar: 'مالي', value: 'Mali' },
  { code: 'MT', en: 'Malta', ar: 'مالطا', value: 'Malta' },
  { code: 'MR', en: 'Mauritania', ar: 'موريتانيا', value: 'Mauritania' },
  { code: 'MU', en: 'Mauritius', ar: 'موريشيوس', value: 'Mauritius' },
  { code: 'MX', en: 'Mexico', ar: 'المكسيك', value: 'Mexico' },
  { code: 'MD', en: 'Moldova', ar: 'مولدوفا', value: 'Moldova' },
  { code: 'MN', en: 'Mongolia', ar: 'منغوليا', value: 'Mongolia' },
  { code: 'ME', en: 'Montenegro', ar: 'الجبل الأسود', value: 'Montenegro' },
  { code: 'MA', en: 'Morocco', ar: 'المغرب', value: 'Morocco' },
  { code: 'MZ', en: 'Mozambique', ar: 'موزمبيق', value: 'Mozambique' },
  { code: 'MM', en: 'Myanmar', ar: 'ميانمار', value: 'Myanmar' },
  { code: 'NA', en: 'Namibia', ar: 'ناميبيا', value: 'Namibia' },
  { code: 'NP', en: 'Nepal', ar: 'نيبال', value: 'Nepal' },
  { code: 'NL', en: 'Netherlands', ar: 'هولندا', value: 'Netherlands' },
  { code: 'NZ', en: 'New Zealand', ar: 'نيوزيلندا', value: 'New Zealand' },
  { code: 'NI', en: 'Nicaragua', ar: 'نيكاراغوا', value: 'Nicaragua' },
  { code: 'NE', en: 'Niger', ar: 'النيجر', value: 'Niger' },
  { code: 'NG', en: 'Nigeria', ar: 'نيجيريا', value: 'Nigeria' },
  { code: 'KP', en: 'North Korea', ar: 'كوريا الشمالية', value: 'North Korea' },
  {
    code: 'MK',
    en: 'North Macedonia',
    ar: 'مقدونيا الشمالية',
    value: 'North Macedonia',
  },
  { code: 'NO', en: 'Norway', ar: 'النرويج', value: 'Norway' },
  { code: 'OM', en: 'Oman', ar: 'عمان', value: 'Oman' },
  { code: 'PK', en: 'Pakistan', ar: 'باكستان', value: 'Pakistan' },
  { code: 'PS', en: 'Palestine', ar: 'فلسطين', value: 'Palestine' },
  { code: 'PA', en: 'Panama', ar: 'بنما', value: 'Panama' },
  { code: 'PY', en: 'Paraguay', ar: 'باراغواي', value: 'Paraguay' },
  { code: 'PE', en: 'Peru', ar: 'بيرو', value: 'Peru' },
  { code: 'PH', en: 'Philippines', ar: 'الفلبين', value: 'Philippines' },
  { code: 'PL', en: 'Poland', ar: 'بولندا', value: 'Poland' },
  { code: 'PT', en: 'Portugal', ar: 'البرتغال', value: 'Portugal' },
  { code: 'QA', en: 'Qatar', ar: 'قطر', value: 'Qatar' },
  { code: 'RO', en: 'Romania', ar: 'رومانيا', value: 'Romania' },
  { code: 'RU', en: 'Russia', ar: 'روسيا', value: 'Russia' },
  { code: 'RW', en: 'Rwanda', ar: 'رواندا', value: 'Rwanda' },
  {
    code: 'SA',
    en: 'Saudi Arabia',
    ar: 'المملكة العربية السعودية',
    value: 'Saudi Arabia',
  },
  { code: 'SN', en: 'Senegal', ar: 'السنغال', value: 'Senegal' },
  { code: 'RS', en: 'Serbia', ar: 'صربيا', value: 'Serbia' },
  { code: 'SG', en: 'Singapore', ar: 'سنغافورة', value: 'Singapore' },
  { code: 'SK', en: 'Slovakia', ar: 'سلوفاكيا', value: 'Slovakia' },
  { code: 'SI', en: 'Slovenia', ar: 'سلوفينيا', value: 'Slovenia' },
  { code: 'SO', en: 'Somalia', ar: 'الصومال', value: 'Somalia' },
  { code: 'ZA', en: 'South Africa', ar: 'جنوب أفريقيا', value: 'South Africa' },
  { code: 'KR', en: 'South Korea', ar: 'كوريا الجنوبية', value: 'South Korea' },
  { code: 'SS', en: 'South Sudan', ar: 'جنوب السودان', value: 'South Sudan' },
  { code: 'ES', en: 'Spain', ar: 'إسبانيا', value: 'Spain' },
  { code: 'LK', en: 'Sri Lanka', ar: 'سريلانكا', value: 'Sri Lanka' },
  { code: 'SD', en: 'Sudan', ar: 'السودان', value: 'Sudan' },
  { code: 'SE', en: 'Sweden', ar: 'السويد', value: 'Sweden' },
  { code: 'CH', en: 'Switzerland', ar: 'سويسرا', value: 'Switzerland' },
  { code: 'SY', en: 'Syria', ar: 'سوريا', value: 'Syria' },
  { code: 'TW', en: 'Taiwan', ar: 'تايوان', value: 'Taiwan' },
  { code: 'TJ', en: 'Tajikistan', ar: 'طاجيكستان', value: 'Tajikistan' },
  { code: 'TZ', en: 'Tanzania', ar: 'تنزانيا', value: 'Tanzania' },
  { code: 'TH', en: 'Thailand', ar: 'تايلاند', value: 'Thailand' },
  { code: 'TN', en: 'Tunisia', ar: 'تونس', value: 'Tunisia' },
  { code: 'TR', en: 'Turkey', ar: 'تركيا', value: 'Turkey' },
  { code: 'TM', en: 'Turkmenistan', ar: 'تركمانستان', value: 'Turkmenistan' },
  { code: 'UG', en: 'Uganda', ar: 'أوغندا', value: 'Uganda' },
  { code: 'UA', en: 'Ukraine', ar: 'أوكرانيا', value: 'Ukraine' },
  {
    code: 'AE',
    en: 'United Arab Emirates',
    ar: 'الإمارات العربية المتحدة',
    value: 'United Arab Emirates',
  },
  {
    code: 'GB',
    en: 'United Kingdom',
    ar: 'المملكة المتحدة',
    value: 'United Kingdom',
  },
  {
    code: 'US',
    en: 'United States',
    ar: 'الولايات المتحدة',
    value: 'United States',
  },
  { code: 'UY', en: 'Uruguay', ar: 'أوروغواي', value: 'Uruguay' },
  { code: 'UZ', en: 'Uzbekistan', ar: 'أوزبكستان', value: 'Uzbekistan' },
  { code: 'VE', en: 'Venezuela', ar: 'فنزويلا', value: 'Venezuela' },
  { code: 'VN', en: 'Vietnam', ar: 'فيتنام', value: 'Vietnam' },
  { code: 'YE', en: 'Yemen', ar: 'اليمن', value: 'Yemen' },
  { code: 'ZM', en: 'Zambia', ar: 'زامبيا', value: 'Zambia' },
  { code: 'ZW', en: 'Zimbabwe', ar: 'زيمبابوي', value: 'Zimbabwe' },
];

/**
 * Get country name by ISO country code
 */
export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find((country) => country.code === code.toUpperCase());
}
