export interface Country {
  en: string;
  ar: string;
  value: string;
}

export const COUNTRIES: Country[] = [
  { en: 'Algeria', ar: 'الجزائر', value: 'Algeria' },
  { en: 'Argentina', ar: 'الأرجنتين', value: 'Argentina' },
  { en: 'Australia', ar: 'أستراليا', value: 'Australia' },
  { en: 'Austria', ar: 'النمسا', value: 'Austria' },
  { en: 'Bahrain', ar: 'البحرين', value: 'Bahrain' },
  { en: 'Bangladesh', ar: 'بنغلاديش', value: 'Bangladesh' },
  { en: 'Belgium', ar: 'بلجيكا', value: 'Belgium' },
  { en: 'Brazil', ar: 'البرازيل', value: 'Brazil' },
  { en: 'Canada', ar: 'كندا', value: 'Canada' },
  { en: 'China', ar: 'الصين', value: 'China' },
  { en: 'Czech Republic', ar: 'التشيك', value: 'Czech Republic' },
  { en: 'Denmark', ar: 'الدنمارك', value: 'Denmark' },
  { en: 'Egypt', ar: 'مصر', value: 'Egypt' },
  { en: 'Finland', ar: 'فنلندا', value: 'Finland' },
  { en: 'France', ar: 'فرنسا', value: 'France' },
  { en: 'Germany', ar: 'ألمانيا', value: 'Germany' },
  { en: 'Greece', ar: 'اليونان', value: 'Greece' },
  { en: 'Hungary', ar: 'المجر', value: 'Hungary' },
  { en: 'India', ar: 'الهند', value: 'India' },
  { en: 'Indonesia', ar: 'إندونيسيا', value: 'Indonesia' },
  { en: 'Iran', ar: 'إيران', value: 'Iran' },
  { en: 'Iraq', ar: 'العراق', value: 'Iraq' },
  { en: 'Ireland', ar: 'أيرلندا', value: 'Ireland' },
  { en: 'Italy', ar: 'إيطاليا', value: 'Italy' },
  { en: 'Japan', ar: 'اليابان', value: 'Japan' },
  { en: 'Jordan', ar: 'الأردن', value: 'Jordan' },
  { en: 'Kuwait', ar: 'الكويت', value: 'Kuwait' },
  { en: 'Lebanon', ar: 'لبنان', value: 'Lebanon' },
  { en: 'Libya', ar: 'ليبيا', value: 'Libya' },
  { en: 'Malaysia', ar: 'ماليزيا', value: 'Malaysia' },
  { en: 'Mexico', ar: 'المكسيك', value: 'Mexico' },
  { en: 'Morocco', ar: 'المغرب', value: 'Morocco' },
  { en: 'Netherlands', ar: 'هولندا', value: 'Netherlands' },
  { en: 'New Zealand', ar: 'نيوزيلندا', value: 'New Zealand' },
  { en: 'Norway', ar: 'النرويج', value: 'Norway' },
  { en: 'Oman', ar: 'عمان', value: 'Oman' },
  { en: 'Pakistan', ar: 'باكستان', value: 'Pakistan' },
  { en: 'Palestine', ar: 'فلسطين', value: 'Palestine' },
  { en: 'Poland', ar: 'بولندا', value: 'Poland' },
  { en: 'Portugal', ar: 'البرتغال', value: 'Portugal' },
  { en: 'Qatar', ar: 'قطر', value: 'Qatar' },
  { en: 'Romania', ar: 'رومانيا', value: 'Romania' },
  { en: 'Russia', ar: 'روسيا', value: 'Russia' },
  { en: 'Saudi Arabia', ar: 'المملكة العربية السعودية', value: 'Saudi Arabia' },
  { en: 'Singapore', ar: 'سنغافورة', value: 'Singapore' },
  { en: 'Somalia', ar: 'الصومال', value: 'Somalia' },
  { en: 'South Africa', ar: 'جنوب أفريقيا', value: 'South Africa' },
  { en: 'South Korea', ar: 'كوريا الجنوبية', value: 'South Korea' },
  { en: 'Spain', ar: 'إسبانيا', value: 'Spain' },
  { en: 'Sudan', ar: 'السودان', value: 'Sudan' },
  { en: 'Sweden', ar: 'السويد', value: 'Sweden' },
  { en: 'Switzerland', ar: 'سويسرا', value: 'Switzerland' },
  { en: 'Syria', ar: 'سوريا', value: 'Syria' },
  { en: 'Thailand', ar: 'تايلاند', value: 'Thailand' },
  { en: 'Tunisia', ar: 'تونس', value: 'Tunisia' },
  { en: 'Turkey', ar: 'تركيا', value: 'Turkey' },
  {
    en: 'United Arab Emirates',
    ar: 'الإمارات العربية المتحدة',
    value: 'United Arab Emirates',
  },
  { en: 'United Kingdom', ar: 'المملكة المتحدة', value: 'United Kingdom' },
  { en: 'United States', ar: 'الولايات المتحدة', value: 'United States' },
  { en: 'Yemen', ar: 'اليمن', value: 'Yemen' },
];
